-- Generated by scripts/gen-normalize-tests.mts from domain/shopping/normalize-cases.json. Do not edit.
begin;
select plan(12);
select is(private.normalize_item_name('Leche'), 'leche', '"Leche"');
select is(private.normalize_item_name('leche '), 'leche', '"leche "');
select is(private.normalize_item_name('LÉCHE'), 'leche', '"LÉCHE"');
select is(private.normalize_item_name('  Pan   de  molde '), 'pan de molde', '"  Pan   de  molde "');
select is(private.normalize_item_name('Piñones'), 'pinones', '"Piñones"');
select is(private.normalize_item_name('Pingüino'), 'pinguino', '"Pingüino"');
select is(private.normalize_item_name('ÁÉÍÓÚ'), 'aeiou', '"ÁÉÍÓÚ"');
select is(private.normalize_item_name('Àgua'), 'agua', '"Àgua"');
select is(private.normalize_item_name('café'), 'cafe', '"café"');
select is(private.normalize_item_name('Ñ'), 'n', '"Ñ"');
select is(private.normalize_item_name('12 huevos'), '12 huevos', '"12 huevos"');
select is(private.normalize_item_name('Tomate' || chr(9) || 'cherry'), 'tomate cherry', '"Tomate\tcherry"');
select * from finish();
rollback;
