// Generates supabase/tests/normalize_cases.test.sql from the shared normalization cases,
// so the SQL function is checked against the same table as the TypeScript one.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

type NormalizeCase = { input: string; expected: string };

const root = join(import.meta.dirname, '..');
const source = 'domain/shopping/normalize-cases.json';
const target = 'supabase/tests/normalize_cases.test.sql';

// Printable ASCII and letters stay literal; everything else (controls, NBSP, U+FEFF...)
// becomes chr(n), so the SQL holds no invisible characters and equals the TS input.
const literal = (value: string) => {
  const parts: string[] = [];
  let text = '';
  const flush = () => {
    if (text !== '') parts.push(`'${text.replaceAll("'", "''")}'`);
    text = '';
  };
  for (const char of value) {
    const code = char.codePointAt(0)!;
    if ((code >= 0x20 && code <= 0x7e) || (code > 0x7f && /\p{L}/u.test(char))) {
      text += char;
    } else {
      flush();
      parts.push(`chr(${code})`);
    }
  }
  flush();
  return parts.length === 0 ? "''" : parts.join(' || ');
};

const cases = JSON.parse(readFileSync(join(root, source), 'utf8')) as NormalizeCase[];

const lines = [
  `-- Generated by scripts/gen-normalize-tests.mts from ${source}. Do not edit.`,
  'begin;',
  `select plan(${cases.length});`,
  ...cases.map(
    (c) =>
      `select is(private.normalize_item_name(${literal(c.input)}), ${literal(c.expected)}, ${literal(JSON.stringify(c.input))});`,
  ),
  'select * from finish();',
  'rollback;',
];

writeFileSync(join(root, target), `${lines.join('\n')}\n`);
