// Generates supabase/tests/normalize_cases.test.sql from the shared normalization cases,
// so the SQL function is checked against the same table as the TypeScript one.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

type NormalizeCase = { input: string; expected: string };

const root = join(import.meta.dirname, '..');
const source = 'domain/shopping/normalize-cases.json';
const target = 'supabase/tests/normalize_cases.test.sql';

// Tabs and newlines are written as chr() calls so the SQL input equals the TS input.
const literal = (value: string) => {
  const parts = value
    .split(/(\t|\n|\r)/)
    .filter((part) => part !== '')
    .map((part) =>
      part === '\t'
        ? 'chr(9)'
        : part === '\n'
          ? 'chr(10)'
          : part === '\r'
            ? 'chr(13)'
            : `'${part.replaceAll("'", "''")}'`,
    );
  return parts.length === 0 ? "''" : parts.join(' || ');
};

const cases = JSON.parse(readFileSync(join(root, source), 'utf8')) as NormalizeCase[];

const lines = [
  `-- Generated by scripts/gen-normalize-tests.mts from ${source}. Do not edit.`,
  'begin;',
  `select plan(${cases.length});`,
  ...cases.map(
    (c) =>
      `select is(private.normalize_item_name(${literal(c.input)}), ${literal(c.expected)}, ${literal(JSON.stringify(c.input))});`,
  ),
  'select * from finish();',
  'rollback;',
];

writeFileSync(join(root, target), `${lines.join('\n')}\n`);
