// Generates supabase/tests/recurrence_cases.test.sql from the shared recurrence cases,
// so the SQL calculation is checked against the same table as the TypeScript one.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

type RecurrenceCase = {
  name: string;
  rule: unknown;
  dueOn: string;
  today: string;
  expected: string;
};

const root = join(import.meta.dirname, '..');
const source = 'domain/recurrence/recurrence-cases.json';
const target = 'supabase/tests/recurrence_cases.test.sql';

const literal = (value: string) => `'${value.replaceAll("'", "''")}'`;

const cases = JSON.parse(readFileSync(join(root, source), 'utf8')) as RecurrenceCase[];

const lines = [
  `-- Generated by scripts/gen-recurrence-tests.mts from ${source}. Do not edit.`,
  'begin;',
  `select plan(${cases.length});`,
  ...cases.map(
    (c) =>
      `select is(private.next_due_on(${literal(JSON.stringify(c.rule))}::jsonb, ${literal(c.dueOn)}::date, ${literal(c.today)}::date), ${literal(c.expected)}::date, ${literal(c.name)});`,
  ),
  'select * from finish();',
  'rollback;',
];

writeFileSync(join(root, target), `${lines.join('\n')}\n`);
