-- Recurring tasks: an occurrence can be skipped as well as completed, and closing
-- (completing or skipping) an occurrence of a recurring series generates the next one
-- in the same transaction. reopen_task withdraws that generated occurrence again.

alter table public.task_occurrences
  add column skipped_at timestamptz,
  add column skipped_by uuid references auth.users on delete set null,
  add column generated_from uuid references public.task_occurrences on delete set null,
  add constraint task_occurrences_completed_or_skipped
    check (not (completed_at is not null and skipped_at is not null)),
  add constraint task_occurrences_skipped_by
    check (skipped_by is null or skipped_at is not null);

-- An occurrence is open when it is neither completed nor skipped. A series has at
-- most one open occurrence, which also makes generating the next one race-free.
create unique index task_occurrences_one_open_per_series on public.task_occurrences (series_id)
  where completed_at is null and skipped_at is null;

drop index public.task_occurrences_open;
create index task_occurrences_open on public.task_occurrences (household_id, due_on)
  where completed_at is null and skipped_at is null;

drop index public.task_occurrences_assignee_open;
create index task_occurrences_assignee_open on public.task_occurrences (assignee_id, due_on)
  where completed_at is null and skipped_at is null;

-- reopen_task finds the occurrence generated from the one being reopened.
create index task_occurrences_generated_from on public.task_occurrences (generated_from)
  where generated_from is not null;

-- Skipped occurrences are history too: they keep their assignee like completed ones.
create or replace function private.unassign_open_tasks()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.task_occurrences
  set assignee_id = null
  where household_id = new.household_id
    and assignee_id = new.user_id
    and completed_at is null
    and skipped_at is null;
  return new;
end;
$$;

-- create_task ----------------------------------------------------------------

drop function public.create_task(uuid, uuid, text, text, uuid, date);

-- Creating a task is idempotent on p_id (the id of the occurrence, generated by the
-- client): repeating a call whose response was lost returns the existing task.
-- Lock order: household row (shared) first, then task rows.
create function public.create_task(
  p_id uuid,
  p_household_id uuid,
  p_title text,
  p_room text,
  p_assignee_id uuid,
  p_due_on date,
  p_recurrence jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  v_title text := btrim(coalesce(p_title, ''));
  v_series uuid;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED' using errcode = 'P0001';
  end if;

  perform 1 from public.households
  where id = p_household_id and deleted_at is null
  for share;

  if not found or not private.is_member(p_household_id) then
    raise exception 'NOT_A_MEMBER' using errcode = 'P0001';
  end if;

  -- Idempotent retry: same household and same author returns the task untouched.
  -- Any other existing id looks like a missing task.
  if exists (select 1 from public.task_occurrences where id = p_id) then
    if exists (
      select 1
      from public.task_occurrences o
      join public.task_series s on s.id = o.series_id and s.household_id = o.household_id
      where o.id = p_id
        and o.household_id = p_household_id
        and s.created_by = v_user
    ) then
      return p_id;
    end if;
    raise exception 'TASK_NOT_FOUND' using errcode = 'P0001';
  end if;

  if char_length(v_title) not between 1 and 100 then
    raise exception 'INVALID_TITLE' using errcode = 'P0001';
  end if;

  if p_room is not null
     and p_room not in ('kitchen', 'bathroom', 'living_room', 'bedroom', 'laundry', 'outdoor', 'other') then
    raise exception 'INVALID_ROOM' using errcode = 'P0001';
  end if;

  if p_assignee_id is not null and not exists (
    select 1
    from public.household_members m
    where m.household_id = p_household_id
      and m.user_id = p_assignee_id
      and m.left_at is null
  ) then
    raise exception 'INVALID_ASSIGNEE' using errcode = 'P0001';
  end if;

  if p_recurrence is not null and not private.valid_recurrence(p_recurrence) then
    raise exception 'INVALID_RECURRENCE' using errcode = 'P0001';
  end if;

  if p_recurrence is not null and p_due_on is null then
    raise exception 'RECURRENCE_NEEDS_DATE' using errcode = 'P0001';
  end if;

  -- Two concurrent calls with the same p_id both pass the exists check above (the
  -- household lock is shared), so the loser hits the primary key of task_occurrences.
  -- Its sub-transaction rolls back the series insert too (no orphan series); the handler
  -- repeats the idempotency check instead of leaking a raw 23505. pgTAP cannot stage
  -- this race.
  begin
    insert into public.task_series (household_id, title, room, recurrence_rule, created_by)
    values (p_household_id, v_title, p_room, p_recurrence, v_user)
    returning id into v_series;

    insert into public.task_occurrences (id, series_id, household_id, due_on, assignee_id)
    values (p_id, v_series, p_household_id, p_due_on, p_assignee_id);
  exception when unique_violation then
    if exists (
      select 1
      from public.task_occurrences o
      join public.task_series s on s.id = o.series_id and s.household_id = o.household_id
      where o.id = p_id
        and o.household_id = p_household_id
        and s.created_by = v_user
    ) then
      return p_id;
    end if;
    raise exception 'TASK_NOT_FOUND' using errcode = 'P0001';
  end;

  return p_id;
end;
$$;

revoke execute on function public.create_task(uuid, uuid, text, text, uuid, date, jsonb) from public, anon;
grant execute on function public.create_task(uuid, uuid, text, text, uuid, date, jsonb) to authenticated;

-- update_task ----------------------------------------------------------------

drop function public.update_task(uuid, text, text, uuid, date);

-- The occurrence's household is read without locking, then the household row is
-- locked (shared) and only then the occurrence (exclusive). The rule belongs to the
-- series: null turns it into a one-off task and keeps every past occurrence.
create function public.update_task(
  p_id uuid,
  p_title text,
  p_room text,
  p_assignee_id uuid,
  p_due_on date,
  p_recurrence jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  v_title text := btrim(coalesce(p_title, ''));
  v_hid uuid;
  v_series uuid;
  v_current uuid;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED' using errcode = 'P0001';
  end if;

  select o.household_id into v_hid
  from public.task_occurrences o
  where o.id = p_id;

  if not found then
    raise exception 'TASK_NOT_FOUND' using errcode = 'P0001';
  end if;

  perform 1 from public.households
  where id = v_hid and deleted_at is null
  for share;

  if not found or not private.is_member(v_hid) then
    raise exception 'TASK_NOT_FOUND' using errcode = 'P0001';
  end if;

  select o.series_id, o.assignee_id into v_series, v_current
  from public.task_occurrences o
  where o.id = p_id
  for update;

  if not found then
    raise exception 'TASK_NOT_FOUND' using errcode = 'P0001';
  end if;

  if char_length(v_title) not between 1 and 100 then
    raise exception 'INVALID_TITLE' using errcode = 'P0001';
  end if;

  if p_room is not null
     and p_room not in ('kitchen', 'bathroom', 'living_room', 'bedroom', 'laundry', 'outdoor', 'other') then
    raise exception 'INVALID_ROOM' using errcode = 'P0001';
  end if;

  -- Re-sending the current assignee is always fine, even if they have left since:
  -- a completed task keeps its assignee for history. Anyone else must be active.
  if p_assignee_id is not null
     and p_assignee_id is distinct from v_current
     and not exists (
    select 1
    from public.household_members m
    where m.household_id = v_hid
      and m.user_id = p_assignee_id
      and m.left_at is null
  ) then
    raise exception 'INVALID_ASSIGNEE' using errcode = 'P0001';
  end if;

  if p_recurrence is not null and not private.valid_recurrence(p_recurrence) then
    raise exception 'INVALID_RECURRENCE' using errcode = 'P0001';
  end if;

  if p_recurrence is not null and p_due_on is null then
    raise exception 'RECURRENCE_NEEDS_DATE' using errcode = 'P0001';
  end if;

  update public.task_series
  set title = v_title, room = p_room, recurrence_rule = p_recurrence
  where id = v_series and household_id = v_hid;

  update public.task_occurrences
  set assignee_id = p_assignee_id, due_on = p_due_on
  where id = p_id;
end;
$$;

revoke execute on function public.update_task(uuid, text, text, uuid, date, jsonb) from public, anon;
grant execute on function public.update_task(uuid, text, text, uuid, date, jsonb) to authenticated;

-- complete_task / skip_task --------------------------------------------------

-- Shared body of complete_task and skip_task. p_today is the caller's local date; it
-- may differ from the server's UTC date by one day either way, never more. Same lock
-- order as the other RPCs; a missing task, a deleted household or a caller who is not
-- an active member are all TASK_NOT_FOUND. Closing an occurrence that is already
-- completed or skipped changes nothing (the first call wins). Otherwise, in a
-- recurring series, the next occurrence is inserted: it inherits the assignee while
-- they are still an active member. The unique open-per-series index backs this up.
create function private.close_occurrence(p_id uuid, p_today date, p_skip boolean)
returns void
language plpgsql
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  v_hid uuid;
  v_occurrence public.task_occurrences%rowtype;
  v_rule jsonb;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED' using errcode = 'P0001';
  end if;

  if p_today is null or abs(p_today - (now() at time zone 'utc')::date) > 1 then
    raise exception 'INVALID_TODAY' using errcode = 'P0001';
  end if;

  select o.household_id into v_hid
  from public.task_occurrences o
  where o.id = p_id;

  if not found then
    raise exception 'TASK_NOT_FOUND' using errcode = 'P0001';
  end if;

  perform 1 from public.households
  where id = v_hid and deleted_at is null
  for share;

  if not found or not private.is_member(v_hid) then
    raise exception 'TASK_NOT_FOUND' using errcode = 'P0001';
  end if;

  select * into v_occurrence
  from public.task_occurrences o
  where o.id = p_id
  for update;

  if not found then
    raise exception 'TASK_NOT_FOUND' using errcode = 'P0001';
  end if;

  select s.recurrence_rule into v_rule
  from public.task_series s
  where s.id = v_occurrence.series_id and s.household_id = v_hid;

  if p_skip and v_rule is null then
    raise exception 'NOT_RECURRING' using errcode = 'P0001';
  end if;

  if v_occurrence.completed_at is not null or v_occurrence.skipped_at is not null then
    return;
  end if;

  if p_skip then
    update public.task_occurrences
    set skipped_at = now(), skipped_by = v_user
    where id = p_id;
  else
    update public.task_occurrences
    set completed_at = now(), completed_by = v_user
    where id = p_id;
  end if;

  if v_rule is not null then
    insert into public.task_occurrences (id, series_id, household_id, due_on, assignee_id, generated_from)
    values (
      gen_random_uuid(),
      v_occurrence.series_id,
      v_hid,
      private.next_due_on(v_rule, coalesce(v_occurrence.due_on, p_today), p_today),
      case
        when v_occurrence.assignee_id is not null and exists (
          select 1
          from public.household_members m
          where m.household_id = v_hid
            and m.user_id = v_occurrence.assignee_id
            and m.left_at is null
        ) then v_occurrence.assignee_id
      end,
      p_id
    );
  end if;
end;
$$;

revoke execute on function private.close_occurrence(uuid, date, boolean) from public, anon, authenticated;

drop function public.complete_task(uuid);

create function public.complete_task(p_id uuid, p_today date)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.close_occurrence(p_id, p_today, false);
end;
$$;

revoke execute on function public.complete_task(uuid, date) from public, anon;
grant execute on function public.complete_task(uuid, date) to authenticated;

-- Only an occurrence of a recurring series can be skipped (NOT_RECURRING otherwise).
create function public.skip_task(p_id uuid, p_today date)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.close_occurrence(p_id, p_today, true);
end;
$$;

revoke execute on function public.skip_task(uuid, date) from public, anon;
grant execute on function public.skip_task(uuid, date) to authenticated;

-- reopen_task ----------------------------------------------------------------

-- Any member can reopen a completed or skipped occurrence. The occurrence generated
-- from it is withdrawn while it is still open; once it has been completed or skipped
-- the series has moved on and the reopen is refused (ALREADY_ADVANCED). An open task
-- must never be assigned to someone who has left, so a departed assignee (kept for
-- history while the task was closed) is cleared.
create or replace function public.reopen_task(p_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  v_hid uuid;
  v_next public.task_occurrences%rowtype;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED' using errcode = 'P0001';
  end if;

  select o.household_id into v_hid
  from public.task_occurrences o
  where o.id = p_id;

  if not found then
    raise exception 'TASK_NOT_FOUND' using errcode = 'P0001';
  end if;

  perform 1 from public.households
  where id = v_hid and deleted_at is null
  for share;

  if not found or not private.is_member(v_hid) then
    raise exception 'TASK_NOT_FOUND' using errcode = 'P0001';
  end if;

  perform 1 from public.task_occurrences o
  where o.id = p_id
  for update;

  if not found then
    raise exception 'TASK_NOT_FOUND' using errcode = 'P0001';
  end if;

  select * into v_next
  from public.task_occurrences o
  where o.generated_from = p_id
  for update;

  if found then
    if v_next.completed_at is not null or v_next.skipped_at is not null then
      raise exception 'ALREADY_ADVANCED' using errcode = 'P0001';
    end if;
    delete from public.task_occurrences where id = v_next.id;
  end if;

  update public.task_occurrences o
  set completed_at = null,
      completed_by = null,
      skipped_at = null,
      skipped_by = null,
      assignee_id = case
        when o.assignee_id is not null and not exists (
          select 1
          from public.household_members m
          where m.household_id = v_hid
            and m.user_id = o.assignee_id
            and m.left_at is null
        ) then null
        else o.assignee_id
      end
  where o.id = p_id and (o.completed_at is not null or o.skipped_at is not null);
end;
$$;
