-- Creating a task is idempotent on p_id (the id of the occurrence, generated by the
-- client): repeating a call whose response was lost returns the existing task.
-- Lock order: household row (shared) first, then task rows.
create function public.create_task(
  p_id uuid,
  p_household_id uuid,
  p_title text,
  p_room text,
  p_assignee_id uuid,
  p_due_on date
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  v_title text := btrim(coalesce(p_title, ''));
  v_series uuid;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED' using errcode = 'P0001';
  end if;

  perform 1 from public.households
  where id = p_household_id and deleted_at is null
  for share;

  if not found or not private.is_member(p_household_id) then
    raise exception 'NOT_A_MEMBER' using errcode = 'P0001';
  end if;

  -- Idempotent retry: same household and same author returns the task untouched.
  -- Any other existing id looks like a missing task.
  if exists (select 1 from public.task_occurrences where id = p_id) then
    if exists (
      select 1
      from public.task_occurrences o
      join public.task_series s on s.id = o.series_id and s.household_id = o.household_id
      where o.id = p_id
        and o.household_id = p_household_id
        and s.created_by = v_user
    ) then
      return p_id;
    end if;
    raise exception 'TASK_NOT_FOUND' using errcode = 'P0001';
  end if;

  if char_length(v_title) not between 1 and 100 then
    raise exception 'INVALID_TITLE' using errcode = 'P0001';
  end if;

  if p_room is not null
     and p_room not in ('kitchen', 'bathroom', 'living_room', 'bedroom', 'laundry', 'outdoor', 'other') then
    raise exception 'INVALID_ROOM' using errcode = 'P0001';
  end if;

  if p_assignee_id is not null and not exists (
    select 1
    from public.household_members m
    where m.household_id = p_household_id
      and m.user_id = p_assignee_id
      and m.left_at is null
  ) then
    raise exception 'INVALID_ASSIGNEE' using errcode = 'P0001';
  end if;

  -- Two concurrent calls with the same p_id both pass the exists check above (the
  -- household lock is shared), so the loser hits the primary key of task_occurrences.
  -- Its sub-transaction rolls back the series insert too (no orphan series); the handler
  -- repeats the idempotency check instead of leaking a raw 23505. pgTAP cannot stage
  -- this race.
  begin
    insert into public.task_series (household_id, title, room, created_by)
    values (p_household_id, v_title, p_room, v_user)
    returning id into v_series;

    insert into public.task_occurrences (id, series_id, household_id, due_on, assignee_id)
    values (p_id, v_series, p_household_id, p_due_on, p_assignee_id);
  exception when unique_violation then
    if exists (
      select 1
      from public.task_occurrences o
      join public.task_series s on s.id = o.series_id and s.household_id = o.household_id
      where o.id = p_id
        and o.household_id = p_household_id
        and s.created_by = v_user
    ) then
      return p_id;
    end if;
    raise exception 'TASK_NOT_FOUND' using errcode = 'P0001';
  end;

  return p_id;
end;
$$;

revoke execute on function public.create_task(uuid, uuid, text, text, uuid, date) from public, anon;
grant execute on function public.create_task(uuid, uuid, text, text, uuid, date) to authenticated;
