-- Shared shopping list. Writes go only through the RPCs below; members read directly.
--
-- Whitespace: names and quantities are trimmed, and names normalized, with one pinned
-- class (space, tab, LF, CR, FF, VT, NBSP), the same one domain/shopping/normalize.ts
-- uses. \s and btrim are avoided on purpose: their class depends on the regex engine
-- or is only the space. The btrim check on the table stays as the spec wrote it: a
-- value trimmed by the pinned class (a superset of the space) always satisfies it.

-- Lowercase, strip Spanish accents, diaeresis and ñ, collapse runs of the pinned class
-- to one space and trim it. Immutable: it computes the generated normalized_name.
create function private.normalize_item_name(p_name text)
returns text
language sql
immutable
parallel safe
set search_path = ''
as $$
  select regexp_replace(
    regexp_replace(
      translate(lower(p_name), 'áéíóúàèìòùäëïöüâêîôûñ', 'aeiouaeiouaeiouaeioun'),
      '[' || chr(32) || chr(9) || chr(10) || chr(13) || chr(12) || chr(11) || chr(160) || ']+',
      ' ',
      'g'
    ),
    '^[' || chr(32) || chr(9) || chr(10) || chr(13) || chr(12) || chr(11) || chr(160) || ']+'
      || '|[' || chr(32) || chr(9) || chr(10) || chr(13) || chr(12) || chr(11) || chr(160) || ']+$',
    '',
    'g'
  );
$$;

-- Trims the pinned class from both ends; inner whitespace is kept as written.
create function private.trim_item_text(p_text text)
returns text
language sql
immutable
parallel safe
set search_path = ''
as $$
  select regexp_replace(
    p_text,
    '^[' || chr(32) || chr(9) || chr(10) || chr(13) || chr(12) || chr(11) || chr(160) || ']+'
      || '|[' || chr(32) || chr(9) || chr(10) || chr(13) || chr(12) || chr(11) || chr(160) || ']+$',
    '',
    'g'
  );
$$;

revoke execute on function private.normalize_item_name(text) from public, anon, authenticated;
revoke execute on function private.trim_item_text(text) from public, anon, authenticated;

create table public.shopping_items (
  id uuid primary key,                       -- generado en el cliente
  household_id uuid not null references public.households on delete cascade,
  name text not null check (char_length(name) between 1 and 60 and name = btrim(name)),
  normalized_name text generated always as (private.normalize_item_name(name)) stored,
  quantity text check (quantity is null or (char_length(quantity) between 1 and 20
                                            and quantity = btrim(quantity))),
  created_by uuid references auth.users on delete set null,
  created_at timestamptz not null default now(),
  bought_at timestamptz,
  bought_by uuid references auth.users on delete set null,
  cleared_at timestamptz,
  check (bought_by is null or bought_at is not null),
  check (cleared_at is null or bought_at is not null)
);

create unique index shopping_items_one_pending on public.shopping_items (household_id, normalized_name)
  where bought_at is null;
create index shopping_items_listed on public.shopping_items (household_id, created_at)
  where cleared_at is null;
create index shopping_items_history on public.shopping_items (household_id, normalized_name);

alter table public.shopping_items enable row level security;

revoke all on public.shopping_items from anon, authenticated;
grant select on public.shopping_items to authenticated;

create policy shopping_items_select_member on public.shopping_items
  for select to authenticated
  using (private.is_member(household_id));

-- add_shopping_item: idempotent on p_id (generated by the client). A name already
-- pending in the household is not added twice: the pending item's id is returned.
-- Lock order: household row (shared), then items.
create function public.add_shopping_item(
  p_id uuid,
  p_household_id uuid,
  p_name text,
  p_quantity text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  v_name text := private.trim_item_text(coalesce(p_name, ''));
  v_quantity text := nullif(private.trim_item_text(p_quantity), '');
  v_pending uuid;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED' using errcode = 'P0001';
  end if;

  perform 1 from public.households
  where id = p_household_id and deleted_at is null
  for share;

  if not found or not private.is_member(p_household_id) then
    raise exception 'NOT_A_MEMBER' using errcode = 'P0001';
  end if;

  -- Retry of a call whose response was lost; an id from another household looks missing.
  if exists (select 1 from public.shopping_items where id = p_id) then
    if exists (
      select 1 from public.shopping_items
      where id = p_id and household_id = p_household_id
    ) then
      return p_id;
    end if;
    raise exception 'ITEM_NOT_FOUND' using errcode = 'P0001';
  end if;

  if char_length(v_name) not between 1 and 60 then
    raise exception 'INVALID_ITEM_NAME' using errcode = 'P0001';
  end if;

  if char_length(v_quantity) > 20 then
    raise exception 'INVALID_QUANTITY' using errcode = 'P0001';
  end if;

  select s.id into v_pending
  from public.shopping_items s
  where s.household_id = p_household_id
    and s.normalized_name = private.normalize_item_name(v_name)
    and s.bought_at is null;

  if found then
    return v_pending;
  end if;

  -- Two concurrent calls (same p_id, or same name) both pass the checks above because
  -- the household lock is shared; the loser hits the primary key or
  -- shopping_items_one_pending and resolves to the row that won. pgTAP cannot stage
  -- this race.
  begin
    insert into public.shopping_items (id, household_id, name, quantity, created_by)
    values (p_id, p_household_id, v_name, v_quantity, v_user);
  exception when unique_violation then
    if exists (
      select 1 from public.shopping_items
      where id = p_id and household_id = p_household_id
    ) then
      return p_id;
    end if;

    select s.id into v_pending
    from public.shopping_items s
    where s.household_id = p_household_id
      and s.normalized_name = private.normalize_item_name(v_name)
      and s.bought_at is null;

    if found then
      return v_pending;
    end if;
    raise exception 'ITEM_NOT_FOUND' using errcode = 'P0001';
  end;

  return p_id;
end;
$$;

revoke execute on function public.add_shopping_item(uuid, uuid, text, text) from public, anon;
grant execute on function public.add_shopping_item(uuid, uuid, text, text) to authenticated;

-- The item RPCs below read the item's household without locking, lock the household
-- row (shared) and then the item (exclusive). A missing item, a deleted household or a
-- caller who is not an active member are all ITEM_NOT_FOUND.

-- set_item_bought: true marks once (the first buyer wins); false unmarks an item not
-- yet archived, unless the same name is pending again, in which case nothing happens.
create function public.set_item_bought(p_id uuid, p_bought boolean)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  v_hid uuid;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED' using errcode = 'P0001';
  end if;

  select s.household_id into v_hid
  from public.shopping_items s
  where s.id = p_id;

  if not found then
    raise exception 'ITEM_NOT_FOUND' using errcode = 'P0001';
  end if;

  perform 1 from public.households
  where id = v_hid and deleted_at is null
  for share;

  if not found or not private.is_member(v_hid) then
    raise exception 'ITEM_NOT_FOUND' using errcode = 'P0001';
  end if;

  perform 1 from public.shopping_items s
  where s.id = p_id
  for update;

  if not found then
    raise exception 'ITEM_NOT_FOUND' using errcode = 'P0001';
  end if;

  if p_bought then
    update public.shopping_items
    set bought_at = now(), bought_by = v_user
    where id = p_id and bought_at is null;
  elsif not p_bought then
    -- A concurrent add of the same name can still win the pending slot between the
    -- not exists and the update; the unique index then rejects it and it is a no-op.
    begin
      update public.shopping_items s
      set bought_at = null, bought_by = null
      where s.id = p_id
        and s.bought_at is not null
        and s.cleared_at is null
        and not exists (
          select 1 from public.shopping_items o
          where o.household_id = s.household_id
            and o.normalized_name = s.normalized_name
            and o.bought_at is null
        );
    exception when unique_violation then
      null;
    end;
  end if;
end;
$$;

revoke execute on function public.set_item_bought(uuid, boolean) from public, anon;
grant execute on function public.set_item_bought(uuid, boolean) to authenticated;

-- update_shopping_item: only pending items can be edited.
create function public.update_shopping_item(p_id uuid, p_name text, p_quantity text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  v_name text := private.trim_item_text(coalesce(p_name, ''));
  v_quantity text := nullif(private.trim_item_text(p_quantity), '');
  v_hid uuid;
  v_bought_at timestamptz;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED' using errcode = 'P0001';
  end if;

  select s.household_id into v_hid
  from public.shopping_items s
  where s.id = p_id;

  if not found then
    raise exception 'ITEM_NOT_FOUND' using errcode = 'P0001';
  end if;

  perform 1 from public.households
  where id = v_hid and deleted_at is null
  for share;

  if not found or not private.is_member(v_hid) then
    raise exception 'ITEM_NOT_FOUND' using errcode = 'P0001';
  end if;

  select s.bought_at into v_bought_at
  from public.shopping_items s
  where s.id = p_id
  for update;

  if not found or v_bought_at is not null then
    raise exception 'ITEM_NOT_FOUND' using errcode = 'P0001';
  end if;

  if char_length(v_name) not between 1 and 60 then
    raise exception 'INVALID_ITEM_NAME' using errcode = 'P0001';
  end if;

  if char_length(v_quantity) > 20 then
    raise exception 'INVALID_QUANTITY' using errcode = 'P0001';
  end if;

  if exists (
    select 1 from public.shopping_items o
    where o.household_id = v_hid
      and o.normalized_name = private.normalize_item_name(v_name)
      and o.bought_at is null
      and o.id <> p_id
  ) then
    raise exception 'ITEM_ALREADY_LISTED' using errcode = 'P0001';
  end if;

  begin
    update public.shopping_items
    set name = v_name, quantity = v_quantity
    where id = p_id;
  exception when unique_violation then
    raise exception 'ITEM_ALREADY_LISTED' using errcode = 'P0001';
  end;
end;
$$;

revoke execute on function public.update_shopping_item(uuid, text, text) from public, anon;
grant execute on function public.update_shopping_item(uuid, text, text) to authenticated;

-- delete_shopping_item: a real delete, by any member.
create function public.delete_shopping_item(p_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  v_hid uuid;
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED' using errcode = 'P0001';
  end if;

  select s.household_id into v_hid
  from public.shopping_items s
  where s.id = p_id;

  if not found then
    raise exception 'ITEM_NOT_FOUND' using errcode = 'P0001';
  end if;

  perform 1 from public.households
  where id = v_hid and deleted_at is null
  for share;

  if not found or not private.is_member(v_hid) then
    raise exception 'ITEM_NOT_FOUND' using errcode = 'P0001';
  end if;

  delete from public.shopping_items where id = p_id;

  if not found then
    raise exception 'ITEM_NOT_FOUND' using errcode = 'P0001';
  end if;
end;
$$;

revoke execute on function public.delete_shopping_item(uuid) from public, anon;
grant execute on function public.delete_shopping_item(uuid) to authenticated;

-- clear_bought_items: archives every bought item not yet archived.
create function public.clear_bought_items(p_household_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
begin
  if v_user is null then
    raise exception 'NOT_AUTHENTICATED' using errcode = 'P0001';
  end if;

  perform 1 from public.households
  where id = p_household_id and deleted_at is null
  for share;

  if not found or not private.is_member(p_household_id) then
    raise exception 'NOT_A_MEMBER' using errcode = 'P0001';
  end if;

  update public.shopping_items
  set cleared_at = now()
  where household_id = p_household_id
    and bought_at is not null
    and cleared_at is null;
end;
$$;

revoke execute on function public.clear_bought_items(uuid) from public, anon;
grant execute on function public.clear_bought_items(uuid) to authenticated;

-- shopping_history: every name the household has listed (pending, bought or archived),
-- grouped by normalized name; name is the most recently written form.
create function public.shopping_history(p_household_id uuid)
returns table (name text, normalized_name text, uses bigint, last_used_at timestamptz)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null then
    raise exception 'NOT_AUTHENTICATED' using errcode = 'P0001';
  end if;

  if not private.is_member(p_household_id) then
    raise exception 'NOT_A_MEMBER' using errcode = 'P0001';
  end if;

  return query
  select
    (array_agg(s.name order by s.created_at desc, s.id desc))[1],
    s.normalized_name,
    count(*),
    max(s.created_at)
  from public.shopping_items s
  where s.household_id = p_household_id
  group by s.normalized_name
  order by 3 desc, 4 desc, 2
  limit 300;
end;
$$;

revoke execute on function public.shopping_history(uuid) from public, anon;
grant execute on function public.shopping_history(uuid) to authenticated;
